name: Release

on:
  push:
    tags:
      - '*'

jobs:
  aur:
    runs-on: ubuntu-latest
    #needs: goreleaser # we don't want to update AUR if goreleaser fails
    container:
      image: archlinux/archlinux:base-devel
    steps:
      - run: |
          pacman -Syu --noconfirm git go openssh pacman-contrib
          useradd -m aur
      # Setup SSH access to aur.archlinux.org
      - uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.AUR_SSH_PRIVATE_KEY }}
      # Now actually clone AUR repo, and update to new version
      - run: |
          export NEW_VERSION="${GITHUB_REF_NAME#v}"
          mkdir -p /root/.ssh && chmod 700 /root/.ssh && touch /root/.ssh/known_hosts && chmod 600 /root/.ssh/known_hosts
          echo "aur.archlinux.org ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIEuBKrPzbawxA/k2g6NcyV5jmqwJ2s+zpgZGZ7tpLIcN" >> /root/.ssh/known_hosts
          # clone repo
          git clone aur@aur.archlinux.org:debricked.git debricked
          chown -R aur debricked/
          cd debricked/
          sudo -u aur NEW_VERSION="${NEW_VERSION}" make update_version
          sudo -u aur make package
          sudo -u aur git diff
          sudo -u aur git config user.email noreply@debricked.com
          sudo -u aur git config user.name "Debricked build bot"
          sudo -u aur SSH_AUTH_SOCK="${SSH_AUTH_SOCK}" NEW_VERSION="${NEW_VERSION}" make push
